title: Wedding Agency
email: krasimira.todorova.petrova@gmail.com
description: Hello world!
baseurl: "/wedding_agency"
url: ""
twitter_username: krasi.t.p
github_username:  krasimira-petrova

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/